### ISSUE TITLE
Setting fields on a listview must be done before any children are added

### ISSUE THREAD

**Issue by bemjb** [mozilla/mortar-layouts#2]
I found out the hard way with setting nextView that it doesn't take effect for list items that are already created, and it looks like that's true for titleField and renderRow as well. Is this intentional? If so, then I'd suggest that the documentation be updated to reflect this. If not, it doesn't look like it would be hard to change the code to update these properties on all of the children when they are changed. (And I wouldn't mind posting a patch for either of these, once it's clear which is correct)

Thanks.

**Comment by jlongster** [comment]
This is not intentional, and I just hit a bug related to this today. I'm sorry I missed this issue for some reason, but I can work on this tomorrow. It shouldn't take long to fix, hopefully by end of day tomorrow. Thanks!

**Comment by bemjb** [comment]
No worries, it was straightforward to work around. Thanks!

**Comment by mcepl** [comment]
Just adding "me too" and wondering how long your days are ;). Just kidding.
